package jp.gr.java_conf.ko_aoki.common.domain;

public class MDeptKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SADB.M_DEPT.DEPT_ID
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SADB.M_DEPT.START_DATE
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	private String startDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SADB.M_DEPT.DEPT_ID
	 * @return  the value of SADB.M_DEPT.DEPT_ID
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SADB.M_DEPT.DEPT_ID
	 * @param deptId  the value for SADB.M_DEPT.DEPT_ID
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SADB.M_DEPT.START_DATE
	 * @return  the value of SADB.M_DEPT.START_DATE
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public String getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SADB.M_DEPT.START_DATE
	 * @param startDate  the value for SADB.M_DEPT.START_DATE
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}
}