package jp.gr.java_conf.ko_aoki.common.domain;

public class MDept extends MDeptKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SADB.M_DEPT.DEPT_NM
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	private String deptNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SADB.M_DEPT.P_DEPT_ID
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	private String pDeptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SADB.M_DEPT.END_DATE
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	private String endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SADB.M_DEPT.VERSION_NO
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	private Long versionNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SADB.M_DEPT.DEPT_NM
	 * @return  the value of SADB.M_DEPT.DEPT_NM
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public String getDeptNm() {
		return deptNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SADB.M_DEPT.DEPT_NM
	 * @param deptNm  the value for SADB.M_DEPT.DEPT_NM
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public void setDeptNm(String deptNm) {
		this.deptNm = deptNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SADB.M_DEPT.P_DEPT_ID
	 * @return  the value of SADB.M_DEPT.P_DEPT_ID
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public String getpDeptId() {
		return pDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SADB.M_DEPT.P_DEPT_ID
	 * @param pDeptId  the value for SADB.M_DEPT.P_DEPT_ID
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public void setpDeptId(String pDeptId) {
		this.pDeptId = pDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SADB.M_DEPT.END_DATE
	 * @return  the value of SADB.M_DEPT.END_DATE
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SADB.M_DEPT.END_DATE
	 * @param endDate  the value for SADB.M_DEPT.END_DATE
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SADB.M_DEPT.VERSION_NO
	 * @return  the value of SADB.M_DEPT.VERSION_NO
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public Long getVersionNo() {
		return versionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SADB.M_DEPT.VERSION_NO
	 * @param versionNo  the value for SADB.M_DEPT.VERSION_NO
	 * @mbggenerated  Wed Dec 11 22:21:06 JST 2013
	 */
	public void setVersionNo(Long versionNo) {
		this.versionNo = versionNo;
	}
}