package jp.gr.java_conf.ko_aoki.common.domain;

public class MMenuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_MENU.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_MENU.MENU_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_MENU.P_MENU_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String pMenuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_MENU.ROLE_ID
     *
     * @return the value of SADB.M_MENU.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_MENU.ROLE_ID
     *
     * @param roleId the value for SADB.M_MENU.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_MENU.MENU_ID
     *
     * @return the value of SADB.M_MENU.MENU_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_MENU.MENU_ID
     *
     * @param menuId the value for SADB.M_MENU.MENU_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_MENU.P_MENU_ID
     *
     * @return the value of SADB.M_MENU.P_MENU_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getpMenuId() {
        return pMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_MENU.P_MENU_ID
     *
     * @param pMenuId the value for SADB.M_MENU.P_MENU_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setpMenuId(String pMenuId) {
        this.pMenuId = pMenuId;
    }
}