package jp.gr.java_conf.ko_aoki.common.domain;

public class MRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_ROLE.ROLE_NM
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String roleNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_ROLE.ROLE_ID
     *
     * @return the value of SADB.M_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_ROLE.ROLE_ID
     *
     * @param roleId the value for SADB.M_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_ROLE.ROLE_NM
     *
     * @return the value of SADB.M_ROLE.ROLE_NM
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getRoleNm() {
        return roleNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_ROLE.ROLE_NM
     *
     * @param roleNm the value for SADB.M_ROLE.ROLE_NM
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setRoleNm(String roleNm) {
        this.roleNm = roleNm;
    }
}