package jp.gr.java_conf.ko_aoki.common.domain;

public class MUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.USER_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.START_DATE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String startDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.USER_ID
     *
     * @return the value of SADB.M_USER.USER_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.USER_ID
     *
     * @param userId the value for SADB.M_USER.USER_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.START_DATE
     *
     * @return the value of SADB.M_USER.START_DATE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.START_DATE
     *
     * @param startDate the value for SADB.M_USER.START_DATE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
}