package jp.gr.java_conf.ko_aoki.common.domain;

public class MUser extends MUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.USERNM_SEI
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String usernmSei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.USERNM_MEI
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String usernmMei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.PASSWORD
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.DEPT_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.END_DATE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SADB.M_USER.VERSION_NO
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    private Long versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.USERNM_SEI
     *
     * @return the value of SADB.M_USER.USERNM_SEI
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getUsernmSei() {
        return usernmSei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.USERNM_SEI
     *
     * @param usernmSei the value for SADB.M_USER.USERNM_SEI
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setUsernmSei(String usernmSei) {
        this.usernmSei = usernmSei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.USERNM_MEI
     *
     * @return the value of SADB.M_USER.USERNM_MEI
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getUsernmMei() {
        return usernmMei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.USERNM_MEI
     *
     * @param usernmMei the value for SADB.M_USER.USERNM_MEI
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setUsernmMei(String usernmMei) {
        this.usernmMei = usernmMei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.PASSWORD
     *
     * @return the value of SADB.M_USER.PASSWORD
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.PASSWORD
     *
     * @param password the value for SADB.M_USER.PASSWORD
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.DEPT_ID
     *
     * @return the value of SADB.M_USER.DEPT_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.DEPT_ID
     *
     * @param deptId the value for SADB.M_USER.DEPT_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.ROLE_ID
     *
     * @return the value of SADB.M_USER.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.ROLE_ID
     *
     * @param roleId the value for SADB.M_USER.ROLE_ID
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.END_DATE
     *
     * @return the value of SADB.M_USER.END_DATE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.END_DATE
     *
     * @param endDate the value for SADB.M_USER.END_DATE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SADB.M_USER.VERSION_NO
     *
     * @return the value of SADB.M_USER.VERSION_NO
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public Long getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SADB.M_USER.VERSION_NO
     *
     * @param versionNo the value for SADB.M_USER.VERSION_NO
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    public void setVersionNo(Long versionNo) {
        this.versionNo = versionNo;
    }
}