package jp.gr.java_conf.ko_aoki.common.mapper;

import java.util.List;
import java.util.Map;

import jp.gr.java_conf.ko_aoki.common.bean.HierarchicalMenuBean;
import jp.gr.java_conf.ko_aoki.common.domain.MMenu;
import jp.gr.java_conf.ko_aoki.common.domain.MMenuExample;
import jp.gr.java_conf.ko_aoki.common.domain.MMenuKey;

import org.apache.ibatis.annotations.Param;

public interface MMenuMapper {

	List<HierarchicalMenuBean> selectHierarchicalMenu(Map<String,String> prm);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int countByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int deleteByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int deleteByPrimaryKey(MMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int insert(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int insertSelective(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    List<MMenu> selectByExample(MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    MMenu selectByPrimaryKey(MMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByExampleSelective(@Param("record") MMenu record, @Param("example") MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByExample(@Param("record") MMenu record, @Param("example") MMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByPrimaryKeySelective(MMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_MENU
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByPrimaryKey(MMenu record);
}