package jp.gr.java_conf.ko_aoki.common.mapper;

import java.util.List;

import jp.gr.java_conf.ko_aoki.common.domain.MRole;
import jp.gr.java_conf.ko_aoki.common.domain.MRoleExample;

import org.apache.ibatis.annotations.Param;

public interface MRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int countByExample(MRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int deleteByExample(MRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int insert(MRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int insertSelective(MRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    List<MRole> selectByExample(MRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    MRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByExampleSelective(@Param("record") MRole record, @Param("example") MRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByExample(@Param("record") MRole record, @Param("example") MRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByPrimaryKeySelective(MRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_ROLE
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByPrimaryKey(MRole record);
}