package jp.gr.java_conf.ko_aoki.common.mapper;

import java.util.List;
import java.util.Map;

import jp.gr.java_conf.ko_aoki.common.bean.MntMUserBean;
import jp.gr.java_conf.ko_aoki.common.domain.MUser;
import jp.gr.java_conf.ko_aoki.common.domain.MUserExample;
import jp.gr.java_conf.ko_aoki.common.domain.MUserKey;

import org.apache.ibatis.annotations.Param;

public interface MUserMapper {

	int countMUserLogin(Map<String,String> prm);

	List<MntMUserBean> selectMntMUserList(Map<String,String> prm);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int countByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int deleteByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int deleteByPrimaryKey(MUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int insert(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int insertSelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    List<MUser> selectByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    MUser selectByPrimaryKey(MUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByExampleSelective(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByExample(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByPrimaryKeySelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SADB.M_USER
     *
     * @mbggenerated Wed Dec 11 22:21:06 JST 2013
     */
    int updateByPrimaryKey(MUser record);
}